# 
		# ,
		# ,
		# ,
		# rombeledit=raw_input("Rombel: "),
		# tmplahiredit=raw_input(d),
		# tgllahiredit=raw_input(e),
		# nikedit=raw_input(f),
		# agamaedit=raw_input(g),
		# kebkhusedit=raw_input(h),
		# alamatedit=raw_input(i),
		# rtedit=raw_input("RT: "),
		# rwedit=raw_input("RW: "),
		# dusunedit=raw_input("Dusun: "),
		# keledit=raw_input("Kelurahan: "),
		# kecedit=raw_input("Kecamatan: "),
		# kodposedit=raw_input("Kode Pos: "),
		# tinggaledit=raw_input("Jenis Tinggal: "),
		# transedit=raw_input("Alat Transportasi: "),
		# hpedit=raw_input("Nomor Telepon atau HP: "),
		# mailedit=raw_input("Email: "),
		# skhunedit=raw_input("SKHUN: "),
		# kpsedit=raw_input("Penerima KPS:(Ya/Tidak)"),
		# nokpsedit=raw_input("Nomor KPS: "),
		# nmayahedit=raw_input(j),
		# thnayahedit=raw_input(k),
		# pendayahedit=raw_input(l),
		# pekayahedit=raw_input(m),
		# pengayahedit=raw_input(n),
		# kebkhusayahedit=raw_input(o),
		# nmibuedit=raw_input(p),
		# thnibuedit=raw_input(q),
		# pendibuedit=raw_input(r),
		# pekibuedit=raw_input(s),
		# pengibuedit=raw_input(t),
		# kebkhusibuedit=raw_input(u),
		# nmawaliedit=raw_input("Nama Wali: "),
		# thnwaliedit=raw_input(v),
		# pendwaliedit=raw_input("Jenjang Pendidikan Wali: "),
		# pekwaliedit=raw_input("Pekerjaan Wali: "),
		# pengwaliedit=raw_input("Penghasilan Wali: "),	